name: pipeline
on: push
jobs:
  build-and-upload-container:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t test_python_app .

      - name: Push Docker image
        run: docker push backpulver/devops_technologies:tagname
