name: pipeline
on: push
jobs:
  build-and-upload-container:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t backpulver/devops_technologies:test_python_app .

      - name: Push Docker image
        run: docker push backpulver/devops_technologies:test_python_app

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Check code style & lint with flake8
        run: flake8

      - name: Install editorconfig-checker
        run: pip install editorconfig-checker

      - name: Check .editorconfig with editorconfig-checker
        run: ec

      - name: Install cli-markdown
        run: npm i -g cli-markdown

      - name: Check markdown files
        run: npm i cli-markdown
